### ISSUE TITLE
Cells have negative area

### ISSUE THREAD

**Issue by felixquinton** [felixquinton/Stage_M2_ICA#2]
I discovered that the face_df dictionary of an organo contains negative values. I attached the code to observe this issue. 
[issue_negative_area.py.tar.gz](https://github.com/felixquinton/Stage_M2_ICA/files/1960971/issue_negative_area.py.tar.gz)

**Comment by glyg** [comment]
I think I fixed that in the latest version of the notebook, it has to do to a bad assignement:
```python
# adjustement
organo.vert_df.loc[organo.apical_verts, organo.coords] = inner_vs[::-1]
organo.vert_df.loc[organo.basal_verts, organo.coords] = outer_vs[::-1]
```
